// <auto-generated />
using System;
using CreditCardRegister.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditCardRegister.API.Migrations
{
    [DbContext(typeof(CreditCardContext))]
    [Migration("20230816143245_Finally")]
    partial class Finally
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CreditCardRegister.API.Entity.CreditCard", b =>
                {
                    b.Property<Guid>("CreditCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreditCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdArchiveLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RegisterCreditCardId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CreditCardId");

                    b.HasIndex("RegisterCreditCardId");

                    b.ToTable("CreditCard");
                });

            modelBuilder.Entity("CreditCardRegister.API.Entity.RegisterCreditCard", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdArchive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BatchId");

                    b.ToTable("BatchCreditCard");
                });

            modelBuilder.Entity("CreditCardRegister.API.Entity.CreditCard", b =>
                {
                    b.HasOne("CreditCardRegister.API.Entity.RegisterCreditCard", "RegisterCreditCard")
                        .WithMany("CreditCardsIds")
                        .HasForeignKey("RegisterCreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisterCreditCard");
                });

            modelBuilder.Entity("CreditCardRegister.API.Entity.RegisterCreditCard", b =>
                {
                    b.Navigation("CreditCardsIds");
                });
#pragma warning restore 612, 618
        }
    }
}
